#!/bin/bash


function obfuscate () {
Cesar=$1
sleep 2
	if [ -e $Nombre ]; then
		rm $Nombre
	fi


touch $Nombre
echo "#!/usr/bin/env bash" >> $Nombre
echo " " >> $Nombre
echo "# Obfuscate by HTR-TECH (Tahmid Rayat)" >> $Nombre
echo "# Github : https://github.com/htr-tech" >> $Nombre
echo " " >> $Nombre
echo "# Sorry Bro ! But You Can not Decrypt It :P" >> $Nombre
echo " " >> $Nombre
printf "HTRTECH=" >> $Nombre
printf "$" >> $Nombre
printf "(mktemp)\n" >> $Nombre
printf "base64 -d  >$" >> $Nombre
printf "{" >> $Nombre
printf "HTRTECH}<<TAHMIDRAYAT\n" >> $Nombre  #DIXIE
echo "$(base64 $file)" >> $Nombre
echo "TAHMIDRAYAT" >> $Nombre
printf "source $" >> $Nombre
printf "{" >> $Nombre
printf "HTRTECH}\n" >> $Nombre
printf "rm -rf $" >> $Nombre
printf "{" >> $Nombre
printf "HTRTECH}" >> $Nombre



}
function verifucar {

	if [ ! -e $file ]; then
		sleep 1
echo
echo "      File Doesn not Exist"
echo
sleep 3
help
	fi
}
function help {
sleep 1
echo "Usage: obfuscate -i <file.sh> -o <new.sh>"
echo
echo "Opcion:      Created by @CesarHackGray"  
echo "  -o, --Nombre                     New Name"
echo "  -i, --Ruta             File to be obfuscated"
echo "           "
echo "   obfuscate -i RutaDelScritp.sh -o (nuevo nombre.sh) "
echo
echo "Visita mi canal en youtube con el comando"
echo "           bash-obfuscate --visitar --channel"
echo "servicio de ayuda"
echo "            bash-obfuscate --chat --Cesar "
echo
 exit
 }

if [ $# -eq 0 ] || [ ! -z $2 ] || [ ! -z $3 ] || [ ! -z $4 ]; then


case $1 in
	"-i")
		;;
	"--chat")
am start -a android.intent.action.VIEW https://t.me/CesarGray
;;
"--visitar")
am start -a android.intent.action.VIEW https://www.youtube.com/channel/UCjs0N8PbEo-se0r_4O_svNQ
;;
	*)
		help
		;;
esac

case $3 in
	"-o")
		;;
	"--Cesar")
am start -a android.intent.action.VIEW https://t.me/CesarGray
;;
"--channel")
	;;
	*)
	help
		;;
esac


for Nombre in $4
do


for file in $2
do
ls &>> /dev/null
done

verifucar 
obfuscate
done
else
	help
fi
