#!/bin/bash

slowprint ()
{
        local i stepping
        stepping="0.01"

        if [ ! "$1" ]; then 
                echo
                return
        fi

        if  (( $# > 1 )) && 
            [[ ($2 = $(echo $2 | grep -oE '[[:digit:]]')) ||
               ($2 = $(echo $2 | grep -oE '[[:digit:]]+\.[[:digit:]]+')) ]] 
            then
                stepping="$2"
        elif (( $# > 1 )); then
                echo "$1"
                echo ".! mm_decho() oops: second argument is invalid!" 1>&2
                echo ".! must be /float but is: \"$2\", leaving function.." 1>&2
                return false 2>/dev/null
        fi

        for i in $(seq 0 $((${#1}-1))); do
                echo -n "${1:$i:1}"
                sleep $stepping
        done
        echo
}

banner() {
clear
printf "\n\e[0m\e[1;92m    ____  _                                 _      \e[0m\n"
printf "\e[0m\e[1;92m   / __ \| |                               | |     \e[0m\n"
printf "\e[0m\e[1;92m  | |  | | |__    _ __ ___  _   _   _______| |__   \e[0m\n"
printf "\e[0m\e[1;96m  | |  | |  _ \  |  _   _ \| | | | |_  / __|  _ \  \e[0m\n"
printf "\e[0m\e[1;96m  | |__| | | | | | | | | | | |_| |  / /\__ \ | | | \e[0m\n"
printf "\e[0m\e[1;93m   \____/|_| |_| |_| |_| |_|\__, | /___|___/_| |_| \e[0m\n"
printf "\e[0m\e[1;93m                             __/ |                 \e[0m\n"
printf "\e[0m\e[1;93m                            |___/                  \e[0m\n"
printf "\e[0m\e[1;96m         CREATED BY HTR-TECH \e[1;91m(\e[1;93m Tahmid Rayat \e[1;91m)\e[0m\n\n"

}

banner
printf " \e[1;91m[\e[1;97m~\e[1;91m]\e[1;93m  "
slowprint "Installing Packages ..."
printf "\e[0m\n"

apt update -y 
apt install git zsh -y
git clone https://github.com/robbyrussell/oh-my-zsh.git $HOME/.oh-my-zsh --depth 1
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.zsh-syntax-highlighting --depth 1

printf "\e[0m\n"
printf " \e[1;91m[\e[1;97m~\e[1;91m]\e[1;93m  "
slowprint "Binding Packets ..."
printf "\e[0m\n"

if [ -d "$HOME/.termux" ]; then
mv "$HOME/.termux" "$HOME/.termux.backup.$(date +%Y.%m.%d-%H)"
fi

if [ ! -d $HOME/.termux ]; then
mkdir $HOME/.termux
fi

cp -f $HOME/.oh-my-zsh/templates/zshrc.zsh-template $HOME/.zshrc
sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="agnoster"/g' $HOME/.zshrc
echo "source $HOME/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> "$HOME/.zshrc"

chsh -s zsh
termux-reload-settings

printf "\e[0m\n"
printf " \e[1;91m[\e[1;97m~\e[1;91m]\e[1;93m  "
slowprint "Installation Completed !!"
printf "\e[0m\n"

printf "\e[0m\n"
printf " \e[1;91m[\e[1;97m~\e[1;91m]\e[1;96m  "
slowprint " RESTARTING !!"
printf "\e[0m\n"
sleep 1
exit
