#!/bin/bash


banner() {
clear
printf "\n\e[0m\e[1;92m    ____  _                                 _      \e[0m\n"
printf "\e[0m\e[1;92m   / __ \| |                               | |     \e[0m\n"
printf "\e[0m\e[1;92m  | |  | | |__    _ __ ___  _   _   _______| |__   \e[0m\n"
printf "\e[0m\e[1;96m  | |  | |  _ \  |  _   _ \| | | | |_  / __|  _ \  \e[0m\n"
printf "\e[0m\e[1;96m  | |__| | | | | | | | | | | |_| |  / /\__ \ | | | \e[0m\n"
printf "\e[0m\e[1;93m   \____/|_| |_| |_| |_| |_|\__, | /___|___/_| |_| \e[0m\n"
printf "\e[0m\e[1;93m                             __/ |                 \e[0m\n"
printf "\e[0m\e[1;93m                            |___/                  \e[0m\n"
printf "\e[0m\e[1;96m         CREATED BY HTR-TECH \e[1;91m(\e[1;93m Tahmid Rayat \e[1;91m)\e[0m\n\n"

}

banner
