#!/bin/bash

banner() {
clear
printf "\n\e[0m\e[1;92m    ____  _                                 _      \e[0m\n"
printf "\e[0m\e[1;92m   / __ \| |                               | |     \e[0m\n"
printf "\e[0m\e[1;92m  | |  | | |__    _ __ ___  _   _   _______| |__   \e[0m\n"
printf "\e[0m\e[1;96m  | |  | |  _ \  |  _   _ \| | | | |_  / __|  _ \  \e[0m\n"
printf "\e[0m\e[1;96m  | |__| | | | | | | | | | | |_| |  / /\__ \ | | | \e[0m\n"
printf "\e[0m\e[1;93m   \____/|_| |_| |_| |_| |_|\__, | /___|___/_| |_| \e[0m\n"
printf "\e[0m\e[1;93m                             __/ |                 \e[0m\n"
printf "\e[0m\e[1;93m                            |___/                  \e[0m\n"
printf "\e[0m\e[1;96m         CREATED BY HTR-TECH \e[1;91m(\e[1;93m Tahmid Rayat \e[1;91m)\e[0m\n\n"

}

banner
printf " \e[1;91m[\e[1;97m~\e[1;91m]\e[1;93m Installing Packages ...\e[0m\n"
printf "\e[0m\n"
sleep 1

apt update -y
termux-setup-storage
apt install git zsh curl -y
git clone https://github.com/robbyrussell/oh-my-zsh.git $HOME/.oh-my-zsh --depth 1
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.zsh-syntax-highlighting --depth 1

if [ -d .termux ]; then
rm -rf .termux
mkdir .termux
fi

curl -o .termux/colors.properties https://raw.githubusercontent.com/htr-tech/release-download/master/oh-my-zsh/colors.properties
curl -o .termux/font.ttf https://github.com/htr-tech/release-download/raw/master/oh-my-zsh/font.ttf


printf "\e[0m\n"
printf " \e[1;91m[\e[1;97m~\e[1;91m]\e[1;93m Binding Packets ...\e[0m\n"
printf "\e[0m\n"

if [ -d "$HOME/.termux" ]; then
rm -rf $HOME/.termux
fi

if [ ! -d $HOME/.termux ]; then
cp -f .termux $HOME/.termux
fi

cp -f $HOME/.oh-my-zsh/templates/zshrc.zsh-template $HOME/.zshrc
chsh -s zsh

termux-setup-storage

sed -i '/^ZSH_THEME/d' "$HOME/.zshrc"
sed -i '1iZSH_THEME="agnoster"' "$HOME/.zshrc"
echo "source $HOME/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> "$HOME/.zshrc"

termux-setup-storage
termux-reload-settings

printf "\e[0m\n"
printf " \e[1;91m[\e[1;97m~\e[1;91m]\e[1;93m Installation Completed !!\e[0m\n"
printf "\e[0m\n"
sleep 2
printf "\e[0m\n"
printf " \e[1;91m[\e[1;97m~\e[1;91m]\e[1;96m RESTARTING !!\e[0m\n"
sleep 2
killall -9 com.termux
