#!/bin/bash

banner() {

clear
printf "\e[0m\n"
printf "\e[0m\e[1;92m   _____           _      \e[0m\e[1;93m  _____        __       \e[0m\n"
printf "\e[0m\e[1;92m  / ____|         | |     \e[0m\e[1;93m |_   _|      / _|      \e[0m\n"
printf "\e[0m\e[1;92m | |  __ _ __ __ _| |__   \e[0m\e[1;93m   | |  _ __ | |_ ___   \e[0m\n"
printf "\e[0m\e[1;92m | | |_ |  __/ _  |  _ \  \e[0m\e[1;93m   | | |  _ \|  _/ _ \  \e[0m\n"
printf "\e[0m\e[1;92m | |__| | | | (_| | |_) | \e[0m\e[1;93m  _| |_| | | | || (_) | \e[0m\n"
printf "\e[0m\e[1;92m  \_____|_|  \__,_|_.__/  \e[0m\e[1;93m |_____|_| |_|_| \___/  \e[0m\n"
printf "\e[0m\n"
printf "\e[0m\e[1;96m    [\e[0m\e[1;97m+\e[0m\e[1;96m]\e[0m\e[1;93m Created By HTR-TECH \e[0m\e[1;91m(\e[0m\e[1;93m Tahmid Rayat \e[0m\e[1;91m)\e[0m\n"

}

banner
printf "\e[0m\n"
printf "\e[0m\e[1;91m [\e[1;97m~\e[1;91m]\e[1;93m Installing Packages ....\e[0m\n"
printf "\e[0m\n"
apt update
apt install curl openssh php unzip -y
printf "\e[0m\n"
printf "\e[0m\e[1;91m [\e[1;97m~\e[1;91m]\e[1;93m Setting Up Environment ....\e[0m\n"
printf "\e[0m\n"

if [[ -d ~/.ssh ]]; then
echo
else
mkdir ~/.ssh
fi

if [[ -e ~/.ssh/known_hosts ]]; then
printf "|1|i5wVhGPb45LMalGcEtx8uLZjpyo=|68jGCnIPnRgGOVdro0jLQCATZ34= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3lJnhW1oCXuAYV9IBdcJA+Vx7AHL5S/ZQvV2fhceOAPgO2kNQZla6xvUwoE4iw8lYu3zoE1KtieCU9yInWOVI6W/wFaT/ETH1tn55T2FVsK/zaxPiHZVJGLPPdEEid0vS2p1JDfc9onZ0pNSHLl1QusIOeMUyZ2bUMMLLgw46KOT9S3s/LmxgoJ3PocVUn5rVXz/Dng7Y8jYNe4IFrZOAUsi7hNBa+OYja6ceefpDvNDEJ1BdhbYfGolBdNA7f+FNl0kfaWru4Cblr843wBe2ckO/sNqgeAMXO/qH+SSgQxUXF2AgAw+TGp3yCIyYoOPvOgvcPsQziJLmDbUuQpnH\n|1|NyJRGLDF8qKI4La6r94ZcbeovY8=|8CZq5pq45rkgSvosAjQ9B+g7qQI= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3lJnhW1oCXuAYV9IBdcJA+Vx7AHL5S/ZQvV2fhceOAPgO2kNQZla6xvUwoE4iw8lYu3zoE1KtieCU9yInWOVI6W/wFaT/ETH1tn55T2FVsK/zaxPiHZVJGLPPdEEid0vS2p1JDfc9onZ0pNSHLl1QusIOeMUyZ2bUMMLLgw46KOT9S3s/LmxgoJ3PocVUn5rVXz/Dng7Y8jYNe4IFrZOAUsi7hNBa+OYja6ceefpDvNDEJ1BdhbYfGolBdNA7f+FNl0kfaWru4Cblr843wBe2ckO/sNqgeAMXO/qH+SSgQxUXF2AgAw+TGp3yCIyYoOPvOgvcPsQziJLmDbUuQpnH\n" >> ~/.ssh/known_hosts
else
printf "|1|i5wVhGPb45LMalGcEtx8uLZjpyo=|68jGCnIPnRgGOVdro0jLQCATZ34= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3lJnhW1oCXuAYV9IBdcJA+Vx7AHL5S/ZQvV2fhceOAPgO2kNQZla6xvUwoE4iw8lYu3zoE1KtieCU9yInWOVI6W/wFaT/ETH1tn55T2FVsK/zaxPiHZVJGLPPdEEid0vS2p1JDfc9onZ0pNSHLl1QusIOeMUyZ2bUMMLLgw46KOT9S3s/LmxgoJ3PocVUn5rVXz/Dng7Y8jYNe4IFrZOAUsi7hNBa+OYja6ceefpDvNDEJ1BdhbYfGolBdNA7f+FNl0kfaWru4Cblr843wBe2ckO/sNqgeAMXO/qH+SSgQxUXF2AgAw+TGp3yCIyYoOPvOgvcPsQziJLmDbUuQpnH\n|1|NyJRGLDF8qKI4La6r94ZcbeovY8=|8CZq5pq45rkgSvosAjQ9B+g7qQI= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3lJnhW1oCXuAYV9IBdcJA+Vx7AHL5S/ZQvV2fhceOAPgO2kNQZla6xvUwoE4iw8lYu3zoE1KtieCU9yInWOVI6W/wFaT/ETH1tn55T2FVsK/zaxPiHZVJGLPPdEEid0vS2p1JDfc9onZ0pNSHLl1QusIOeMUyZ2bUMMLLgw46KOT9S3s/LmxgoJ3PocVUn5rVXz/Dng7Y8jYNe4IFrZOAUsi7hNBa+OYja6ceefpDvNDEJ1BdhbYfGolBdNA7f+FNl0kfaWru4Cblr843wBe2ckO/sNqgeAMXO/qH+SSgQxUXF2AgAw+TGp3yCIyYoOPvOgvcPsQziJLmDbUuQpnH\n" >> ~/.ssh/known_hosts
fi

