#!/bin/bash

banner() {

clear
printf "\e[0m\n"
printf "\e[0m\e[1;92m   _____           _      \e[0m\e[1;93m  _____        __       \e[0m\n"
printf "\e[0m\e[1;92m  / ____|         | |     \e[0m\e[1;93m |_   _|      / _|      \e[0m\n"
printf "\e[0m\e[1;92m | |  __ _ __ __ _| |__   \e[0m\e[1;93m   | |  _ __ | |_ ___   \e[0m\n"
printf "\e[0m\e[1;92m | | |_ |  __/ _  |  _ \  \e[0m\e[1;93m   | | |  _ \|  _/ _ \  \e[0m\n"
printf "\e[0m\e[1;92m | |__| | | | (_| | |_) | \e[0m\e[1;93m  _| |_| | | | || (_) | \e[0m\n"
printf "\e[0m\e[1;92m  \_____|_|  \__,_|_.__/  \e[0m\e[1;93m |_____|_| |_|_| \___/  \e[0m\n"
printf "\e[0m\n"
printf "\e[0m\e[1;96m    [\e[0m\e[1;97m+\e[0m\e[1;96m]\e[0m\e[1;93m Created By HTR-TECH \e[0m\e[1;91m(\e[0m\e[1;93m Tahmid Rayat \e[0m\e[1;91m)\e[0m\n"

}

banner
printf "\e[0m\n"
printf "\e[0m\e[1;91m [\e[1;97m~\e[1;91m]\e[1;93m Installing Packages ....\e[0m\n"
printf "\e[0m\n"
apt update
apt install curl openssh php unzip -y
printf "\e[0m\n"
printf "\e[0m\e[1;91m [\e[1;97m~\e[1;91m]\e[1;93m Setting Up Environment ....\e[0m\n"
printf "\e[0m\n"


if [[ -d .server ]]; then
printf ""
else
mkdir .server
fi

if [[ -e .server/ngrok ]]; then
printf ""
else
arch=$(uname -a | grep -o 'arm' | head -n1)
arch2=$(uname -a | grep -o 'Android' | head -n1)
if [[ $arch == *'arm'* ]] || [[ $arch2 == *'Android'* ]] ; then
curl -LO https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip > /dev/null 2>&1

if [[ -e ngrok-stable-linux-arm.zip ]]; then
unzip ngrok-stable-linux-arm.zip > /dev/null 2>&1
mv ngrok .server
rm -rf ngrok-stable-linux-arm.zip
chmod +x .server/ngrok
else
printf " \n\e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;93m Error \e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;96m Install Ngrok Manually.\e[0m\n"
exit 1
fi


else
curl -LO https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-386.zip > /dev/null 2>&1 
if [[ -e ngrok-stable-linux-386.zip ]]; then
unzip ngrok-stable-linux-386.zip > /dev/null 2>&1
mv ngrok .server
rm -rf ngrok-stable-linux-386.zip
chmod +x .server/ngrok
else
printf " \n\e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;93m Error \e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;96m Install Ngrok Manually.\e[0m\n"
exit 1
fi
fi
fi

printf "\e[0m\n"
printf "\e[0m\e[1;91m [\e[1;97m~\e[1;91m]\e[1;93m Installation Completed !! \e[0m\n"
printf "\e[0m\n"
sleep 2
printf "\e[0m\e[1;91m [\e[1;97m~\e[1;91m]\e[1;93m Type \e[1;96mbash grab.sh \e[1;93mto run GRAB INFO !! \e[0m\n"
printf "\e[0m\n"
printf "\e[0m\n"
